[main] Update 2026-05-19.22 (#529)
Reference commit: c1bea8472a

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -90,7 +90,7 @@ commands:
             - docker_log_into_gcr
             - setup_qemu_and_buildx
             - run:
-                command: ./docker/canton/build_canton_image.sh <<parameters.nightly_release>>
+                command: PUBLISH_IMAGES=true ./docker/canton/build_canton_image.sh <<parameters.nightly_release>>
                 name: Build and publish docker base image
     check_number_of_successes:
         description: |
@@ -1756,6 +1756,20 @@ jobs:
                     - scaladoc.tar.gz
                 root: target
             - cleanup_test_job
+    check_todos:
+        executor: canton-medium-docker
+        steps:
+            - checkout:
+                method: blobless
+            - run:
+                command: |
+                    # Run the todo checker only on the private repo
+                    # TODO(i30871): Enable again on all projects
+                    if [ "${CIRCLE_PROJECT_USERNAME}" = "DACH-NY" ]; then
+                      .ci/nix-exec amm .circleci/todo-script/src/checkTodos.sc
+                    fi
+                name: Run the todo checker
+            - slack_red_main_with_volunteer
     compile:
         executor: canton-xlarge-docker
         steps:
@@ -2380,6 +2394,15 @@ jobs:
         steps:
             - checkout:
                 method: blobless
+            - run:
+                command: |
+                    if [[ "$CIRCLE_BRANCH" == *"#"* || "$CIRCLE_BRANCH" == *"%"* ]]; then
+                      echo "ERROR: Branch name '$CIRCLE_BRANCH' contains a URL-special character ('#' or '%')."
+                      echo "'#' is treated as a URL fragment delimiter and '%' as a percent-encoding prefix by azcopy, breaking Azure cache operations."
+                      echo "Please rename your branch without '#' or '%'."
+                      exit 1
+                    fi
+                name: Check branch name does not contain URL-special characters
             - check_pr_skip_ci
             - restore_sbt_cache
             - execute_sbt_command:
@@ -2404,14 +2427,6 @@ jobs:
                     diff shell.nix /tmp/shell.nix || exit 1
                     diff -r nix /tmp/nix || exit 1
                 name: Check that Nix definitions are up to date
-            - run:
-                command: |
-                    # Run the todo checker only on the private repo
-                    # TODO(i30871): Enable again on all projects
-                    if [ "${CIRCLE_PROJECT_USERNAME}" = "DACH-NY" ]; then
-                      .ci/nix-exec amm .circleci/todo-script/src/checkTodos.sc
-                    fi
-                name: Run the todo checker
             - slack_red_main_with_volunteer
     tag_new_releases:
         executor: canton-small-docker
@@ -2455,6 +2470,25 @@ jobs:
                 num_parallel_tasks: "1"
                 num_test_buckets: "8"
                 timeout: 1h
+            - slack_red_main_with_volunteer
+    test_docker_images:
+        executor: canton-large-docker-on-cci
+        steps:
+            - attach_workspace:
+                at: /tmp/workspace
+            - checkout:
+                method: blobless
+            - obtain_release_suffix:
+                is_manual: false
+                is_nightly_workflow: false
+            - setup_remote_docker
+            - run:
+                command: ./docker/canton/build_canton_image.sh false
+                name: Build and test docker images (without publishing)
+            - store_artifacts:
+                destination: docker-ping-test-logs
+                path: docker/canton/tests/ping/ci-artifacts/compose-logs
+                when: always
             - slack_red_main_with_volunteer
     test_flake_fix_many_times:
         executor: canton-xlarge-docker-with-postgres-toxiproxy
@@ -2868,6 +2902,21 @@ workflows:
                 is_nightly_workflow: false
                 requires:
                     - compile
+            - test_docker_images:
+                context:
+                    - datadog
+                    - artifactory
+                    - azure-self-cache
+                    - maven-mirror
+                    - da-images
+                filters:
+                    branches:
+                        ignore:
+                            - /^gh-readonly-queue\/main\/.*/
+                    tags:
+                        only: /^v.*/
+                requires:
+                    - package_community
             - verify_circleci_config_and_compliance_label:
                 filters:
                     branches:
@@ -2888,6 +2937,18 @@ workflows:
                     branches:
                         ignore:
                             - /^gha-migration\/.*/
+            - check_todos:
+                context:
+                    - datadog
+                    - artifactory
+                    - azure-self-cache
+                    - maven-mirror
+                    - da-images
+                filters:
+                    branches:
+                        ignore:
+                            - /^gha-migration\/.*/
+                            - main
             - protobuf_continuity:
                 context:
                     - datadog
